version: '3'
services:
    nginx:
        image: nginx:alpine 
        ports:
            - "5043:443"
        links: 
            - registry:registry
        volumes:
            - ./auth:/etc/nginx/conf.d
            - ./auth/nginx.conf:/etc/nginx/niginx.conf:ro
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
    registry: 
        image: registry:2
        volumes:
            - ./data:/var/lib/registry
    certbot:
        image: certbot/certbot
        volumes: 
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot



