version: '3'
services:
    nginx:
        image: nginx:alpine 
        container_name: proxy
        ports:
            - "5043:443"
        links: 
            - registry:registry
        volumes:
            - ./auth:/etc/nginx/conf.d
            - ./auth/nginx.conf:/etc/nginx/niginx.conf:ro
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
    registry: 
        image: registry:2
        volumes:
            - ./data:/var/lib/registry
    certbot:
        image: certbot/certbot
        volumes: 
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
            - web-root:/var/www/html
        depends_on: 
            - webserver
        command: certonly --webroot --webroot-path=/var/www/html --email dhb220@gmail.com --agree-tos --no-eff-email --staging -d docker.cmpartners.biz  -d www.docker.cmpartners.biz

    webserver:
        image: nginx:mainline-alpine
        container_name: web
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - web-root:/var/www/html
            - ./nginx-conf:/etc/nginx/conf.d
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
    volumes:
        certbot-etc:
        certbot-var:
        web-root:
            driver: local
            driver_opts:
                type: none
                device: /home/derekbroadwater/debian/views/
                o: bind




